spring.application.name=creatorstore

# db info
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# Optional (recommended if using PostgreSQL)
spring.datasource.driver-class-name=org.postgresql.Driver

# hibernate orm configuration
#data def language auto updates in the db if any updates
spring.jpa.hibernate.ddl-auto=update
# format the sql what we wrote
spring.jpa.properties.hibernate.format_sql=true
spring.show-sql= true
